### ISSUE TITLE
Register Helpers missing from the Handlebars object. v2.4

### ISSUE THREAD

**Issue by augurone** [assemble/assemble-handlebars#25]
Error loading helpers from file: ~/bower_components/{helper}.js
TypeError: Object #<Object> has no method 'registerHelper'

So I logged the object to see what was there, and there is not registerHelper on the object.

{
  init: [Function],
  compile: [Function],
  render: [Function],
  registerFunctions: [Function],
  registerPartial: [Function] 
}

**Comment by Psykoral** [comment]
:+1: definitely seeing this too. Causing errors in builds.

**Comment by doowb** [comment]
`handlebars` property is missing from the object. we'll get it fixed soon.

**Comment by doowb** [comment]
Try 0.2.5 and let me know if that fixes the issue.

**Comment by augurone** [comment]
:thumbsup: That did the trick, thanks for your responsiveness.

**Comment by Psykoral** [comment]
thanks for the quick turn around!
