### ISSUE TITLE
Blockquotes not rendering

### ISSUE THREAD

**Issue by davidsinclair** [assemble/assemble-handlebars#30]
Hi,

I am having a problem getting blockquotes to render correctly.  The following code illustrates the problem,  when I run it the output is:
```
<h1 id="heading">heading</h1>
<p> &gt; pull quote</p>
```
i.e. the > is being escaped rather than rendered as a blockquote.  

Any help greatly appreciated,

David

```
var assemble = require('assemble-handlebars');
assemble.init({
    marked: { sanitize: false, gfm: true}
});
var templateSrc =  '{{#markdown}}{{body}}{{/markdown}} ';
var doc = { body: "#heading\n\n > pull quote" };

assemble.compile(templateSrc, {}, 
	function(ex, template) {		
		assemble.render(template, doc, function(ex, renderedContent) {
                console.log(renderedContent);	
            });
	});
```

**Comment by doowb** [comment]
Sorry, I missed this before. Looks like it was answered in https://github.com/assemble/assemble/issues/744.
